'use client';

import { useEffect, useRef } from 'react';
import TikTokEmbed from './TikTokEmbed';

interface TikTokVideoModalProps {
    url: string | null;
    onClose: () => void;
}

/**
 * Custom modal for opening TikTok video fullscreen.
 * PhotoSwipe can't be reused here: its engine expects an image or native
 * <video> with known dimensions, not third-party iframe dynamically
 * generated by TikTok's embed.js script.
 *
 * TikTok embed is only mounted when modal is open (url not null),
 * to avoid loading one iframe per visible card in slider.
 */
export default function TikTokVideoModal({ url, onClose }: TikTokVideoModalProps) {
    const overlayRef = useRef<HTMLDivElement>(null);
    const isOpen = url !== null;

    // Close via Escape key while modal is open.
    useEffect(() => {
        if (!isOpen) return;

        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'Escape') onClose();
        };

        document.addEventListener('keydown', handleKeyDown);
        return () => document.removeEventListener('keydown', handleKeyDown);
    }, [isOpen, onClose]);

    // Prevent page scrolling behind modal while open.
    useEffect(() => {
        if (!isOpen) return;
        const previousOverflow = document.body.style.overflow;
        document.body.style.overflow = 'hidden';
        return () => {
            document.body.style.overflow = previousOverflow;
        };
    }, [isOpen]);

    if (!isOpen) return null;

    const handleOverlayClick = (e: React.MouseEvent<HTMLDivElement>) => {
        // Close only if click targets overlay itself, not its content.
        if (e.target === overlayRef.current) onClose();
    };

    return (
        <div
            ref={overlayRef}
            className="tiktok-modal-overlay"
            onClick={handleOverlayClick}
            role="dialog"
            aria-modal="true"
            aria-label="Play video"
        >
            <button
                type="button"
                className="tiktok-modal-close"
                onClick={onClose}
                aria-label="Close video"
            >
                ×
            </button>

            <div className="tiktok-modal-content">
                <TikTokEmbed url={url} />
            </div>
        </div>
    );
}